//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acciones
    {
        public int id { get; set; }
        public string dimension { get; set; }
        public string estado { get; set; }
        public string accion { get; set; }
        public string medidasPrevencion { get; set; }
        public string responsable { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    }
}
