//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acciones()
        {
            this.evidencia_acciones = new HashSet<evidencia_acciones>();
        }
    
        public int id { get; set; }
        public string dimension { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string accion { get; set; }
        public string medidasPrevencion { get; set; }
        public string responsable { get; set; }
        public Nullable<System.DateTime> fecha_compromiso { get; set; }
        public string tipo { get; set; }
        public string color { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<bool> status { get; set; }
        public string categoria { get; set; }
        public string dominio { get; set; }
        public Nullable<short> year { get; set; }
        public Nullable<int> idCentro { get; set; }
        public string date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evidencia_acciones> evidencia_acciones { get; set; }
    }
}
