//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_perfil
    {
        public int id { get; set; }
        public string cedula { get; set; }
        public string celular { get; set; }
        public string celcontacto { get; set; }
        public string contacto { get; set; }
        public Nullable<int> idUsuario { get; set; }
    }
}
