//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuestionarioATS
    {
        public int id { get; set; }
        public string traumatico { get; set; }
        public System.DateTime fechao { get; set; }
        public string hora { get; set; }
        public string descripcion { get; set; }
        public int personas { get; set; }
        public int tipo { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
