//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuestionarioDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuestionarioDetalle()
        {
            this.respuestaEmpDetalle = new HashSet<respuestaEmpDetalle>();
        }
    
        public int id { get; set; }
        public int noReactivo { get; set; }
        public string Reactivo { get; set; }
        public int idCuestionario { get; set; }
        public int idPosiblesResp { get; set; }
        public int idCategoria { get; set; }
        public Nullable<int> idDimencion { get; set; }
    
        public virtual posiblesRespuestas posiblesRespuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestaEmpDetalle> respuestaEmpDetalle { get; set; }
        public virtual cuestionario cuestionario { get; set; }
        public virtual dimencion dimencion { get; set; }
        public virtual EncabezadoCuestionario EncabezadoCuestionario { get; set; }
    }
}
