//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.logRespuestaEmpleado = new HashSet<logRespuestaEmpleado>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string curp { get; set; }
        public string nss { get; set; }
        public string telefono { get; set; }
        public string contacto { get; set; }
        public string celcontacto { get; set; }
        public int idEmpresa { get; set; }
        public int idCentroTrabajo { get; set; }
        public int idEstatus { get; set; }
        public int idUsuario { get; set; }
        public Nullable<bool> aceptoPolitica { get; set; }
        public string area_funcion { get; set; }
    
        public virtual centroTrabajo centroTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logRespuestaEmpleado> logRespuestaEmpleado { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual cstatus cstatus { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
