//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.centroTrabajo = new HashSet<centroTrabajo>();
            this.empleado = new HashSet<empleado>();
            this.encargadosEmpresa = new HashSet<encargadosEmpresa>();
            this.respuestaEmpleado = new HashSet<respuestaEmpleado>();
        }
    
        public int id { get; set; }
        public string razonc { get; set; }
        public string razons { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string actividad { get; set; }
        public string puesto { get; set; }
        public string rfc { get; set; }
        public string img { get; set; }
        public System.DateTime fecha { get; set; }
        public int idStatus { get; set; }
        public Nullable<bool> ctAdministraEmpleados { get; set; }
        public string contrato { get; set; }
        public string nombrejerarquia { get; set; }
        public string puestojerarquia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<centroTrabajo> centroTrabajo { get; set; }
        public virtual cstatus cstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encargadosEmpresa> encargadosEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestaEmpleado> respuestaEmpleado { get; set; }
    }
}
