//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaSugerencias
    {
        public int id { get; set; }
        public string sugerencia { get; set; }
        public string categoria { get; set; }
        public Nullable<short> year { get; set; }
        public string rol { get; set; }
        public string color { get; set; }
        public string dominio { get; set; }
        public string dimension { get; set; }
    }
}
