//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencia_acciones
    {
        public int Id { get; set; }
        public string folio { get; set; }
        public string tipo { get; set; }
        public string actividad { get; set; }
        public System.DateTime fecha { get; set; }
        public string status { get; set; }
        public string comentario { get; set; }
        public string linked { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> regitro { get; set; }
        public Nullable<int> idAccion { get; set; }
    
        public virtual acciones acciones { get; set; }
    }
}
