//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posiblesRespDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public posiblesRespDetalle()
        {
            this.respuestaEmpDetalle = new HashSet<respuestaEmpDetalle>();
        }
    
        public int id { get; set; }
        public string Respuesta { get; set; }
        public short valor { get; set; }
        public int idEncabezado { get; set; }
    
        public virtual posiblesRespuestas posiblesRespuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestaEmpDetalle> respuestaEmpDetalle { get; set; }
    }
}
