//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestaEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public respuestaEmpleado()
        {
            this.respuestaEmpDetalle = new HashSet<respuestaEmpDetalle>();
        }
    
        public int id { get; set; }
        public string sexo { get; set; }
        public string edad { get; set; }
        public string estadoCivil { get; set; }
        public string antiguedad { get; set; }
        public string tiempoPuestoActual { get; set; }
        public string tiempoExperienciaLaboral { get; set; }
        public string escolaridad { get; set; }
        public string tipoJornada { get; set; }
        public string tipoContratacion { get; set; }
        public string tipoPersonal { get; set; }
        public string tieneDiscapacidad { get; set; }
        public string discapacidad { get; set; }
        public string realizaRotacion { get; set; }
        public int idCuestionario { get; set; }
        public int idEmpresa { get; set; }
        public int idCentroTrabajo { get; set; }
        public string parteSectores { get; set; }
        public string sector { get; set; }
        public string existePolitica { get; set; }
        public string existeCodigoEtica { get; set; }
        public string existeComite { get; set; }
        public string existeMecanismo { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string dondeTrabajo { get; set; }
    
        public virtual centroTrabajo centroTrabajo { get; set; }
        public virtual cuestionario cuestionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestaEmpDetalle> respuestaEmpDetalle { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
