//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestaEmpDetalle
    {
        public int id { get; set; }
        public int idResuestaEmpleado { get; set; }
        public int idPregunta { get; set; }
        public Nullable<int> idRespuesta { get; set; }
    
        public virtual cuestionarioDetalle cuestionarioDetalle { get; set; }
        public virtual posiblesRespDetalle posiblesRespDetalle { get; set; }
        public virtual respuestaEmpleado respuestaEmpleado { get; set; }
    }
}
