//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultados_por_usuario_025
    {
        public int id { get; set; }
        public string curp { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int idEmpresa { get; set; }
        public int idCentroTrabajo { get; set; }
        public string valores { get; set; }
    }
}
