//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rhcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultados_nom035
    {
        public int idResuestaEmpleado { get; set; }
        public int idPregunta { get; set; }
        public Nullable<int> idRespuesta { get; set; }
        public short valor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int idCentroTrabajo { get; set; }
        public int idEmpresa { get; set; }
        public int id_cabecera { get; set; }
        public string cabecera_descripcion { get; set; }
        public Nullable<int> idDimencion { get; set; }
        public string dimencion_descripcion { get; set; }
        public int idDominio { get; set; }
        public string dominio_descripcion { get; set; }
        public int idCategoria { get; set; }
        public string categoria_descripcion { get; set; }
        public int id { get; set; }
        public string curp { get; set; }
        public Nullable<int> year { get; set; }
        public string antiguedad { get; set; }
        public string comentario { get; set; }
        public string discapacidad { get; set; }
        public string dondeTrabajo { get; set; }
        public string edad { get; set; }
        public string escolaridad { get; set; }
        public string estadoCivil { get; set; }
        public string existeCodigoEtica { get; set; }
        public string existeComite { get; set; }
        public string existeMecanismo { get; set; }
        public string existePolitica { get; set; }
        public int idRespuestaEmpleado { get; set; }
        public int idCuestionario { get; set; }
        public string parteSectores { get; set; }
        public string realizaRotacion { get; set; }
        public string sector { get; set; }
        public string sexo { get; set; }
        public string tiempoExperienciaLaboral { get; set; }
        public string tiempoPuestoActual { get; set; }
        public string tieneDiscapacidad { get; set; }
        public string tipoContratacion { get; set; }
        public string tipoJornada { get; set; }
        public string tipoPersonal { get; set; }
    }
}
